site_name: MiniFRC Wiki
site_url: https://minifrc.com
repo_name: ddthj/minifrc-com
repo_url: https://github.com/ddthj/minifrc-com
edit_uri: https://github.com/ddthj/minifrc-com/edit/main/docs

theme:
  name: material
  logo: assets/logo/favicon_rwb.png
  favicon: assets/logo/favicon_rwb.png
  palette:
    scheme: slate
  features:
    # Enables navigation without page reload
    - navigation.instant
    # Don't include the index in navigation
    - navigation.indexes
    # Suggest pages when typing in the search bar
    - search.suggest
    # Enable the 'edit this page' button
    - content.action.edit
    
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html